import { TaskStatus } from './task.entity';

export const MOCK_TASKS = [
  {
    creator: 'nacharkina',
    executor: null,
    type: 'KPO',
    number: '17636/611-26',
    materialName: 'Углепластик ВКУ-61/ВТкУ-5',
    topic: '0024-26 от 05.06.2026 г.',
    testMethod: 'Изгиб',
    standard: 'ASTM D7264',
    temperatureConditions: [
      { temperature: 20, quantity: 6, modulus: true },
      { temperature: 120, quantity: 6, modulus: true },
    ],
    isUrgent: false,
    status: TaskStatus.PENDING,
  },

  {
    creator: 'kovalenko',
    executor: null,
    type: 'KPO',
    number: '17637/610-26',
    materialName: 'Стеклопластик ВПС-77',
    topic: '0025-26 от 06.06.2026 г.',
    testMethod: 'Сжатие',
    standard: 'ГОСТ 25.602-80',
    temperatureConditions: [{ temperature: 20, quantity: 5, modulus: false }],
    isUrgent: true,
    urgentReason: 'Срочная партия',
    status: TaskStatus.PENDING,
  },

  {
    creator: 'kovalenko',
    executor: null,
    type: 'KPO',
    number: '17638/610-26',
    materialName: 'Сферопластик ВПЗ-21',
    topic: '0026-26 от 06.06.2026 г.',
    testMethod: 'Отрыв',
    standard: 'ГОСТ 14760-69',
    temperatureConditions: [{ temperature: 20, quantity: 8, modulus: false }],
    isUrgent: false,
    status: TaskStatus.PENDING,
  },

  {
    creator: 'nacharkina',
    executor: null,
    type: 'KPO',
    number: '17639/611-26',
    materialName: 'Углепластик ВКУ-61/ВТкУ-5',
    topic: '0027-26 от 07.06.2026 г.',
    testMethod: 'Сдвиг в плоскости',
    standard: 'ASTM D3518',
    temperatureConditions: [
      { temperature: -60, quantity: 6, modulus: true },
      { temperature: 20, quantity: 6, modulus: true },
    ],
    isUrgent: false,
    status: TaskStatus.PENDING,
  },

  {
    creator: 'kovalenko',
    executor: null,
    type: 'KPO',
    number: '17640/610-26',
    materialName: 'ВПС-77',
    topic: '0028-26 от 07.06.2026 г.',
    testMethod: 'Разрыв ткани',
    standard: 'ГОСТ 6943.10-2015',
    temperatureConditions: [{ temperature: 20, quantity: 10, modulus: false }],
    isUrgent: false,
    status: TaskStatus.PENDING,
  },

  {
    creator: 'nacharkina',
    executor: 'gubin',
    type: 'KPO',
    number: '17641/611-26',
    materialName: 'Углепластик ВКУ-61/ВТкУ-5',
    topic: '0029-26',
    testMethod: 'Растяжение',
    standard: 'ГОСТ Р 56785-2015',
    temperatureConditions: [{ temperature: 20, quantity: 6, modulus: true }],
    isUrgent: false,
    status: TaskStatus.ACTIVE,
    acceptedAt: new Date('2026-06-08'),
  },

  {
    creator: 'kovalenko',
    executor: 'ivanov',
    type: 'KPO',
    number: '17642/610-26',
    materialName: 'ВПЗ-21',
    topic: '0030-26',
    testMethod: 'Изгиб',
    standard: 'ГОСТ 4648-2014',
    temperatureConditions: [{ temperature: 20, quantity: 8, modulus: true }],
    isUrgent: true,
    urgentReason: 'Требуется протокол',
    status: TaskStatus.ACTIVE,
    acceptedAt: new Date('2026-06-07'),
  },

  {
    creator: 'nacharkina',
    executor: 'gubin',
    type: 'KPO',
    number: '17643/611-26',
    materialName: 'Углепластик ВКУ-61/ВТкУ-5',
    topic: '0031-26',
    testMethod: 'Сжатие',
    standard: 'ASTM D6641',
    temperatureConditions: [
      { temperature: 20, quantity: 6, modulus: false },
      { temperature: 120, quantity: 6, modulus: false },
    ],
    isUrgent: false,
    status: TaskStatus.ACTIVE,
    acceptedAt: new Date('2026-06-06'),
  },

  {
    creator: 'kovalenko',
    executor: 'ivanov',
    type: 'KPO',
    number: '17644/610-26',
    materialName: 'Стеклопластик ВПС-77',
    topic: '0032-26',
    testMethod: 'Межслойный сдвиг',
    standard: 'ASTM D2344',
    temperatureConditions: [{ temperature: 20, quantity: 8, modulus: false }],
    isUrgent: false,
    status: TaskStatus.ACTIVE,
    acceptedAt: new Date('2026-06-05'),
  },

  {
    creator: 'nacharkina',
    executor: 'gubin',
    type: 'KPO',
    number: '17645/611-26',
    materialName: 'Углепластик ВКУ-61/ВТкУ-5',
    topic: '0033-26',
    testMethod: 'Поперечное растяжение',
    standard: 'ASTM D7291',
    temperatureConditions: [{ temperature: 20, quantity: 6, modulus: true }],
    isUrgent: false,
    status: TaskStatus.ACTIVE,
    acceptedAt: new Date('2026-06-04'),
  },

  {
    creator: 'nacharkina',
    executor: 'ivanov',
    type: 'KPO',
    number: '17646/611-26',
    materialName: 'Углепластик ВКУ-61/ВТкУ-5',
    topic: '0034-26',
    testMethod: 'Сжатие после удара',
    standard: 'ГОСТ 33495-2015',
    temperatureConditions: [{ temperature: 20, quantity: 6, modulus: false }],
    isUrgent: false,
    status: TaskStatus.COMPLETED,
    acceptedAt: new Date('2026-05-20'),
    completedAt: new Date('2026-05-28'),
  },

  {
    creator: 'kovalenko',
    executor: 'gubin',
    type: 'KPO',
    number: '17647/610-26',
    materialName: 'ВПС-77',
    topic: '0035-26',
    testMethod: 'Изгиб',
    standard: 'ГОСТ Р 56810-2015',
    temperatureConditions: [{ temperature: 20, quantity: 10, modulus: true }],
    isUrgent: false,
    status: TaskStatus.COMPLETED,
    acceptedAt: new Date('2026-05-18'),
    completedAt: new Date('2026-05-25'),
  },

  {
    creator: 'nacharkina',
    executor: 'ivanov',
    type: 'KPO',
    number: '17648/611-26',
    materialName: 'Углепластик ВКУ-61/ВТкУ-5',
    topic: '0036-26',
    testMethod: 'Сдвиг по Иосипеску',
    standard: 'ASTM D5379',
    temperatureConditions: [{ temperature: 20, quantity: 6, modulus: true }],
    isUrgent: true,
    urgentReason: 'Отчёт заказчику',
    status: TaskStatus.COMPLETED,
    acceptedAt: new Date('2026-05-15'),
    completedAt: new Date('2026-05-22'),
  },

  {
    creator: 'kovalenko',
    executor: 'gubin',
    type: 'KPO',
    number: '17649/610-26',
    materialName: 'ВПЗ-21',
    topic: '0037-26',
    testMethod: 'Отслаивание',
    standard: 'ОСТ 1 90315-83',
    temperatureConditions: [{ temperature: 20, quantity: 8, modulus: false }],
    isUrgent: false,
    status: TaskStatus.COMPLETED,
    acceptedAt: new Date('2026-05-14'),
    completedAt: new Date('2026-05-20'),
  },

  {
    creator: 'nacharkina',
    executor: 'ivanov',
    type: 'KPO',
    number: '17650/611-26',
    materialName: 'Углепластик ВКУ-61/ВТкУ-5',
    topic: '0038-26',
    testMethod: 'Удар падающим грузом',
    standard: 'ASTM D7136',
    temperatureConditions: [{ temperature: 20, quantity: 6, modulus: false }],
    isUrgent: false,
    status: TaskStatus.COMPLETED,
    acceptedAt: new Date('2026-05-10'),
    completedAt: new Date('2026-05-17'),
  },
];
