export const TEST_METHODS = [
  // Растяжение

  {
    id: 'tension_gost_r_56785',
    name: 'Растяжение',
    standard: 'ГОСТ Р 56785-2015',
    supportsModulus: true,
    defaultModulus: true,
    testTemperatureMin: -60,
    testTemperatureMax: 350,
    modulusTemperatureMax: 150,
    calculationType: 'tension_pcm',
  },
  {
    id: 'tension_astm_d3039',
    name: 'Растяжение',
    standard: 'ASTM D3039',
    supportsModulus: true,
    defaultModulus: true,
    testTemperatureMin: -60,
    testTemperatureMax: 350,
    modulusTemperatureMax: 150,
    calculationType: 'tension_pcm',
  },
  {
    id: 'tension_gost_11262',
    name: 'Растяжение',
    standard: 'ГОСТ 11262-2017',
    supportsModulus: true,
    defaultModulus: true,
    testTemperatureMin: -60,
    testTemperatureMax: 200,
    modulusTemperatureMax: 150,
    calculationType: 'tension_pcm',
  },
  {
    id: 'tension_gost_15873',
    name: 'Растяжение',
    standard: 'ГОСТ 15873-2017',
    supportsModulus: false,
    defaultModulus: false,
    testTemperatureMin: -60,
    testTemperatureMax: 200,
    modulusTemperatureMax: 0,
    calculationType: 'tension_pcm',
  },

  // Сжатие

  {
    id: 'compression_gost_r_56812',
    name: 'Сжатие',
    standard: 'ГОСТ Р 56812-2015',
    supportsModulus: true,
    defaultModulus: false,
    testTemperatureMin: -60,
    testTemperatureMax: 350,
    modulusTemperatureMax: 150,
    calculationType: 'compression_pcm',
  },
  {
    id: 'compression_astm_d6641',
    name: 'Сжатие',
    standard: 'ASTM D6641',
    supportsModulus: true,
    defaultModulus: false,
    testTemperatureMin: -60,
    testTemperatureMax: 350,
    modulusTemperatureMax: 150,
    calculationType: 'compression_pcm',
  },
  {
    id: 'compression_gost_4651',
    name: 'Сжатие',
    standard: 'ГОСТ 4651-2014',
    supportsModulus: false,
    defaultModulus: false,
    testTemperatureMin: -60,
    testTemperatureMax: 350,
    modulusTemperatureMax: 0,
    calculationType: 'cubes',
  },
  {
    id: 'compression_astm_d695',
    name: 'Сжатие',
    standard: 'ASTM D695',
    supportsModulus: false,
    defaultModulus: false,
    testTemperatureMin: -60,
    testTemperatureMax: 300,
    modulusTemperatureMax: 0,
    calculationType: 'cubes',
  },
  {
    id: 'compression_gost_26605',
    name: 'Сжатие',
    standard: 'ГОСТ 26605-2017',
    supportsModulus: false,
    defaultModulus: false,
    testTemperatureMin: -60,
    testTemperatureMax: 300,
    modulusTemperatureMax: 0,
    calculationType: 'cubes',
  },
  {
    id: 'compression_gost_33519',
    name: 'Сжатие',
    standard: 'ГОСТ 33519-2015',
    supportsModulus: true,
    defaultModulus: false,
    testTemperatureMin: -60,
    testTemperatureMax: 300,
    modulusTemperatureMax: 150,
    calculationType: 'compression_pcm',
  },
  {
    id: 'compression_gost_23206',
    name: 'Сжатие',
    standard: 'ГОСТ 23206-2017',
    supportsModulus: false,
    defaultModulus: false,
    testTemperatureMin: -60,
    testTemperatureMax: 300,
    modulusTemperatureMax: 0,
    calculationType: 'cubes',
  },
  {
    id: 'compression_gost_25_602',
    name: 'Сжатие',
    standard: 'ГОСТ 25.602-80',
    supportsModulus: true,
    defaultModulus: false,
    testTemperatureMin: -60,
    testTemperatureMax: 300,
    modulusTemperatureMax: 150,
    calculationType: 'compression_pcm',
  },

  // ИЗГИБ

  {
    id: 'flexure_gost_r_56810',
    name: 'Изгиб',
    standard: 'ГОСТ Р 56810-2015',
    supportsModulus: true,
    defaultModulus: true,
    testTemperatureMin: -60,
    testTemperatureMax: 350,
    modulusTemperatureMax: 350,
    calculationType: 'flexure_pcm',
  },
  {
    id: 'flexure_gost_r_56805',
    name: 'Изгиб',
    standard: 'ГОСТ Р 56805-2015',
    supportsModulus: true,
    defaultModulus: true,
    testTemperatureMin: -60,
    testTemperatureMax: 350,
    modulusTemperatureMax: 350,
    calculationType: 'flexure_pcm',
  },
  {
    id: 'flexure_gost_r_56788',
    name: 'Изгиб',
    standard: 'ГОСТ Р 56788-2015',
    supportsModulus: true,
    defaultModulus: true,
    testTemperatureMin: -60,
    testTemperatureMax: 350,
    modulusTemperatureMax: 350,
    calculationType: 'flexure_pcm',
  },
  {
    id: 'flexure_astm_d7264',
    name: 'Изгиб',
    standard: 'ASTM D7264',
    supportsModulus: true,
    defaultModulus: true,
    testTemperatureMin: -60,
    testTemperatureMax: 350,
    modulusTemperatureMax: 350,
    calculationType: 'flexure_pcm',
  },
  {
    id: 'flexure_gost_4648',
    name: 'Изгиб',
    standard: 'ГОСТ 4648-2014',
    supportsModulus: true,
    defaultModulus: true,
    testTemperatureMin: -60,
    testTemperatureMax: 350,
    modulusTemperatureMax: 350,
    calculationType: 'flexure_pcm',
  },
  {
    id: 'flexure_astm_d790',
    name: 'Изгиб',
    standard: 'ASTM D790',
    supportsModulus: true,
    defaultModulus: true,
    testTemperatureMin: -60,
    testTemperatureMax: 350,
    modulusTemperatureMax: 350,
    calculationType: 'flexure_pcm',
  },
  {
    id: 'flexure_gost_25_604',
    name: 'Изгиб',
    standard: 'ГОСТ 25.604-82',
    supportsModulus: true,
    defaultModulus: true,
    testTemperatureMin: -60,
    testTemperatureMax: 350,
    modulusTemperatureMax: 350,
    calculationType: 'flexure_pcm',
  },

  // СДВИГ ПО ИОСИПЕСКУ

  {
    id: 'iosipescu_gost_r_56799',
    name: 'Сдвиг по Иосипеску',
    standard: 'ГОСТ Р 56799-2015',
    supportsModulus: true,
    defaultModulus: true,
    testTemperatureMin: -60,
    testTemperatureMax: 300,
    modulusTemperatureMax: 150,
    calculationType: 'inplane_shear_butterfly',
  },
  {
    id: 'iosipescu_astm_d5379',
    name: 'Сдвиг по Иосипеску',
    standard: 'ASTM D5379',
    supportsModulus: true,
    defaultModulus: true,
    testTemperatureMin: -60,
    testTemperatureMax: 300,
    modulusTemperatureMax: 150,
    calculationType: 'inplane_shear_butterfly',
  },

  // МЕЖСЛОЙНЫЙ СДВИГ

  {
    id: 'interlaminar_shear_gost_r_57745',
    name: 'Межслойный сдвиг',
    standard: 'ГОСТ Р 57745-2017',
    supportsModulus: false,
    defaultModulus: false,
    testTemperatureMin: -60,
    testTemperatureMax: 350,
    modulusTemperatureMax: 0,
    calculationType: 'interlaminar_shear',
  },
  {
    id: 'interlaminar_shear_gost_32659',
    name: 'Межслойный сдвиг',
    standard: 'ГОСТ 32659-2014',
    supportsModulus: false,
    defaultModulus: false,
    testTemperatureMin: -60,
    testTemperatureMax: 350,
    modulusTemperatureMax: 0,
    calculationType: 'interlaminar_shear',
  },
  {
    id: 'interlaminar_shear_astm_d2344',
    name: 'Межслойный сдвиг',
    standard: 'ASTM D2344',
    supportsModulus: false,
    defaultModulus: false,
    testTemperatureMin: -60,
    testTemperatureMax: 350,
    modulusTemperatureMax: 0,
    calculationType: 'interlaminar_shear',
  },

  // СДВИГ В ПЛОСКОСТИ

  {
    id: 'inplane_shear_gost_r_57207',
    name: 'Сдвиг в плоскости',
    standard: 'ГОСТ Р 57207-2016',
    supportsModulus: true,
    defaultModulus: true,
    testTemperatureMin: -60,
    testTemperatureMax: 300,
    modulusTemperatureMax: 150,
    calculationType: 'inplane_shear_butterfly',
  },
  {
    id: 'inplane_shear_astm_d7078',
    name: 'Сдвиг в плоскости',
    standard: 'ASTM D7078',
    supportsModulus: true,
    defaultModulus: true,
    testTemperatureMin: -60,
    testTemperatureMax: 300,
    modulusTemperatureMax: 150,
    calculationType: 'inplane_shear_butterfly',
  },
  {
    id: 'inplane_shear_gost_32658',
    name: 'Сдвиг в плоскости',
    standard: 'ГОСТ 32658-2014',
    supportsModulus: true,
    defaultModulus: true,
    testTemperatureMin: -60,
    testTemperatureMax: 350,
    modulusTemperatureMax: 150,
    calculationType: 'inplane_shear_45',
  },
  {
    id: 'inplane_shear_astm_d3518',
    name: 'Сдвиг в плоскости',
    standard: 'ASTM D3518',
    supportsModulus: true,
    defaultModulus: true,
    testTemperatureMin: -60,
    testTemperatureMax: 350,
    modulusTemperatureMax: 150,
    calculationType: 'inplane_shear_45',
  },

  // УДАР ПАДАЮЩИМ ГРУЗОМ

  {
    id: 'drop_weight_impact_astm_d7136',
    name: 'Удар падающим грузом',
    standard: 'ASTM D7136',
    supportsModulus: false,
    defaultModulus: false,
    testTemperatureMin: 20,
    testTemperatureMax: 150,
    modulusTemperatureMax: 0,
    calculationType: 'drop_weight_impact',
  },
  {
    id: 'drop_weight_impact_gost_33496',
    name: 'Удар падающим грузом',
    standard: 'ГОСТ 33496-2015',
    supportsModulus: false,
    defaultModulus: false,
    testTemperatureMin: 20,
    testTemperatureMax: 150,
    modulusTemperatureMax: 0,
    calculationType: 'drop_weight_impact',
  },

  // СЖАТИЕ ПОСЛЕ УДАРА

  {
    id: 'cai_astm_d7137',
    name: 'Сжатие после удара',
    standard: 'ASTM D7137',
    supportsModulus: false,
    defaultModulus: false,
    testTemperatureMin: -60,
    testTemperatureMax: 300,
    modulusTemperatureMax: 0,
    calculationType: 'compression_after_impact',
  },
  {
    id: 'cai_gost_33495',
    name: 'Сжатие после удара',
    standard: 'ГОСТ 33495-2015',
    supportsModulus: false,
    defaultModulus: false,
    testTemperatureMin: -60,
    testTemperatureMax: 300,
    modulusTemperatureMax: 0,
    calculationType: 'compression_after_impact',
  },

  // ОТСЛАИВАНИЕ

  {
    id: 'peel_ost_190315',
    name: 'Отслаивание',
    standard: 'ОСТ 1 90315-83',
    supportsModulus: false,
    defaultModulus: false,
    testTemperatureMin: -60,
    testTemperatureMax: 200,
    modulusTemperatureMax: 0,
    calculationType: 'peel',
  },

  // ОТРЫВ

  {
    id: 'pull_off_gost_14760',
    name: 'Отрыв',
    standard: 'ГОСТ 14760-69',
    supportsModulus: false,
    defaultModulus: false,
    testTemperatureMin: -60,
    testTemperatureMax: 300,
    modulusTemperatureMax: 0,
    calculationType: 'pull_off',
  },

  // РАЗРЫВ ТКАНИ

  {
    id: 'fabric_tear_gost_29104',
    name: 'Разрыв ткани',
    standard: 'ГОСТ 29104.4-91',
    supportsModulus: false,
    defaultModulus: false,
    testTemperatureMin: -60,
    testTemperatureMax: 350,
    modulusTemperatureMax: 0,
    calculationType: 'fabric_tear',
  },
  {
    id: 'fabric_tear_gost_6943',
    name: 'Разрыв ткани',
    standard: 'ГОСТ 6943.10-2015',
    supportsModulus: false,
    defaultModulus: false,
    testTemperatureMin: -60,
    testTemperatureMax: 350,
    modulusTemperatureMax: 0,
    calculationType: 'fabric_tear',
  },

  // ПОПЕРЕЧНОЕ РАСТЯЖЕНИЕ

  {
    id: 'through_thickness_tension_astm_d7291',
    name: 'Поперечное растяжение',
    standard: 'ASTM D7291',
    supportsModulus: true,
    defaultModulus: true,
    testTemperatureMin: -60,
    testTemperatureMax: 300,
    modulusTemperatureMax: 150,
    calculationType: 'through_thickness_tension',
  },
];
